[package]
name = "company-control"
version = "0.1.0"
authors = ["fernandoeckstein <fernando_eckstein@hotmail.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
lazy_static = "1.4.0"
regex = "1"